### ISSUE TITLE
A lot of errors and warnings when compiled

### ISSUE THREAD

**Issue by oliora** [jandrewrogers/AquaHash#1]
I've tried to use AquaHash in my code and got tons of errors and warnings (that turned into errors since we're strict on it). We compile with gcc4.9 with flags `-Werror -pedantic -Wpedantic -Wall`.

```
.../aquahash.h: In static member function ‘static __m128i AquaHash::SmallKeyAlgorithm(const uint8_t*, size_t, __m128i)’:
.../aquahash.h:78:103: error: overflow in implicit constant conversion [-Werror=overflow]
                                       0x6a6c, 0x9527, *reinterpret_cast<const uint16_t*>(ptr8), 0xac2e);
                                                                                                       ^
.../aquahash.h:78:103: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:78:103: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:78:103: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:78:103: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
                                      0x1e, 0x86, 0x3f, 0x24, 0xb2, 0xa8, *reinterpret_cast<const uint8_t*>(ptr8), 0x31);
                                                                                                                       ^
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h:85:119: error: overflow in implicit constant conversion [-Werror=overflow]
.../aquahash.h: In static member function ‘static __m128i AquaHash::LargeKeyAlgorithm(const uint8_t*, size_t, __m128i)’:
.../aquahash.h:104:111: error: missing braces around initializer for ‘__m128 {aka __vector(4) float}’ [-Werror=missing-braces]
                             _mm_xor_si128(initialize, _mm_set_epi64x(0xcc96ed1674eaaa03, 0x1e863f24b2a8316a)) };
                                                                                                               ^
.../aquahash.h:104:111: error: cannot convert ‘__m128i {aka __vector(2) long long int}’ to ‘float’ in initialization
.../aquahash.h:104:111: error: cannot convert ‘__m128i {aka __vector(2) long long int}’ to ‘float’ in initialization
.../aquahash.h:104:111: error: cannot convert ‘__m128i {aka __vector(2) long long int}’ to ‘float’ in initialization
.../aquahash.h:104:111: error: cannot convert ‘__m128i {aka __vector(2) long long int}’ to ‘float’ in initialization
.../aquahash.h:109:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[0] = _mm_aesenc_si128(block[0], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:110:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[1] = _mm_aesenc_si128(block[1], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:111:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[2] = _mm_aesenc_si128(block[2], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:112:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[3] = _mm_aesenc_si128(block[3], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:117:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[0] = _mm_aesenc_si128(block[0], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:118:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[1] = _mm_aesenc_si128(block[1], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:122:76: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[2] = _mm_aesenc_si128(block[2], _mm_loadu_si128(ptr128++));
                                                                            ^
.../aquahash.h:130:52: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[3] = _mm_aesenc_si128(block[3], b);
                                                    ^
.../aquahash.h:137:52: error: cannot convert ‘__m128 {aka __vector(4) float}’ to ‘__m128i {aka __vector(2) long long int}’ for argument ‘1’ to ‘__m128i _mm_aesenc_si128(__m128i, __m128i)’
             block[0] = _mm_aesenc_si128(block[0], b);
                                                    ^
...
```

**Comment by jandrewrogers** [comment]
Hey Andrey,

This is almost certainly a gcc artifact, it compiles with no warnings using clang in strict mode. This code came from a C++17 code base where we stopped supporting gcc 7 due to repeated compiler bugs. I don’t know if it will compile on gcc 4.9 but I can take a look at getting a clean build under a recent version of gcc at a minimum since this is a relatively small bit of code. I forgot that I hadn’t compiled with gcc in quite some time.

Cheers,
Andrew

**Comment by paulie-g** [comment]
Most of those errors are down to '__m128 block[4]' instead of '__m128i block[4]' in AquaHash::LargeKeyAlgorithm

**Comment by hungptit** [comment]
@jandrewrogers  I have seen this problem in all of my Linux test environments and I have fixed it by switching to clang before seeing this ticket. Could you update the doc to let users know that they should either use clang or figure out the problem by themselves?
